# Generated by Django 4.1.7 on 2023-03-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking_unit.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='services/videos')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='booking_unit.service')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='request',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='name',
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(null=True, upload_to='business/images'),
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(null=True, upload_to='request/images'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(default='-', upload_to='services/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='video',
            field=models.FileField(null=True, upload_to='request/videos'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking_unit.service'),
        ),
        migrations.DeleteModel(
            name='ServiceVideos',
        ),
    ]
