# Generated by Django 4.1.7 on 2023-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_unit', '0002_review_servicevideo_remove_business_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transport_per_km',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='transport_per_km',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
